---
title: "The 2021 World Trade Report is out"
description: |
  I had the honour to contribute to the writing of this year's edition of the World Trade Report, the flagship economic publication of the World Trade Organization.  The report explores the role of trade, trade policy and international cooperation in building economic resilience in a world marked by increasing risks. In this article, I briefly outline my contributions on risk trends and policy responses to shocks.
  
author:
  - name: Francesco S. Bellelli
date: 11-16-2021
categories:
  - economics
  - trade
preview: "https://www.wto.org/images/img_bkshop/wtr21_e.jpg"
output:
  distill::distill_article:
    toc: true
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px}
</style>


<div class = "blue"><center> The full 2021 World Trade Report is available **[here](https://www.wto.org/english/res_e/publications_e/wtr21_e.htm)**. </center></div>
<br>


## Key messages of the report

*The COVID-19 pandemic and the prospect of increasingly frequent and more intense natural and man-made disasters raise important questions about the resilience of the global economy to such shocks. The World Trade Report 2021 explores the role of trade, trade policy and international cooperation in building and supporting economic resilience.*

*The report conveys three main messages: first, today’s hyper-connected global economy, characterized by deep trade links, has made the world more vulnerable to shocks, but also more resilient to them when they strike; second, policies which aim to increase economic resilience by unwinding trade integration –-- for example, by re-shoring production and promoting self-sufficiency --- can often have the opposite effect, effectively reducing economic resilience; and third, strengthening economic resilience will require more global cooperation.*

## My contribution on risks and policy response 

I contributed to writing section B of the report. In particular, I authored the part exploring the sources and trends in risks, and the part on policy responses to shocks. 

In the report, we highlight that risks are constantly evolving and are increasingly interlinked. For example, climate change is driving increases in extreme weather events, such as droughts, cyclones and floods, which can have devastating economic and social effects. Human encroachment on animal habitats can increase the risks of spreading zoonotic diseases, which could potentially lead to another pandemic. Although safer production processes have reduced the frequency of technological and industrial disasters, incidences of cyber-attacks and data fraud are expected to continue to increase. Rising inequality, increasing economic fragility, and growing political uncertainty and geopolitical tensions are augmenting the risk of conflicts and violence. While there is a tendency to look at these risks individually, they can interact with each other and create cascading risks.

These risks materialise into shocks which have considerable human, economic and environmental damages. The economic policy responses to shocks is usually aimed at cushioning the impact of the shocks. We can decompose economic disruption into: 1) demand shocks, 2) supply shocks and 3) increased uncertainty. In the the report we describe how different policies have been used to tackle these disruptions and note that shocks usually involve a combination of the three elements. Similarly, trade policy response is rarely entirely restrictive or liberalising.  On the one hand, protectionism is seen as a way of prioritising domestic economic activity, while, on the the other hand, trade-opening often plays a crucial role in solving sudden demand-supply mismatches and emergency situations. 


## The launch of the report
<iframe width="560" height="400" src="https://www.youtube.com/embed/RQDm3yBvrRI" frameborder="0" allowfullscreen>
</iframe>

