---
title: "Publications"
description: |
  Find out more about my research projects
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Research interests & ongoing projects

I am currently working in the credit risk methodology team of UBS as a specialist for climate change risk. As such, I am investigating approaches to quantify and incorporate climate-related risks in the banks' models. 

In addition to the above, I am also fascinated by recent developments in AI and its applications to macroeconomic forecasting and issues in international and environmental economics.



## Notes and scientific papers

Xu, A., Tresa, E., **Bellelli, F.S.**, Bacchetta, M., Monteiro, J.A.. Trade and the transfer of climate-related technologies. *World Trade Organization, Trade and climate change information brief* (*Under internal review*).


**Bellelli, F.S.**, Xu, A. Why should we fish for an agreement? An economic analysis of fisheries subsidies. *(to be published as WTO discussion paper)*

**Bellelli, F.S.**, Monteiro, J.A. and Xu, A. Assessing the environmental effectiveness of environmental provisions in Regional Trade Agreements. *(Drafting in progress)*


**Bellelli, F.S.**, Scarpa, R. and Aftab, A. (2023) An empirical analysis of participation in environmental agreements. *Journal of Environmental Economics and Management*, 118, 102783. https://www.sciencedirect.com/science/article/abs/pii/S0095069623000013.
<a href="papers/Ratification_paper.pdf"><button>PDF</button></a>
<a href="papers/ratification paper appendix.zip"><button>Appendix</button></a>
<a href="ratification-data.html"><button>Data</button></a>
<a href="https://drive.google.com/file/d/1b_4h66745Hk7M_SR5JPXaB8ViJ-GMRRH/view?usp=sharing"><button>Replication files</button></a>

**Bellelli, F.S.**, Scarpa, R. and Aftab, A. (2023) The participation dilemma: A survey of the empirical literature on international environmental agreement ratification, *Review of Environmental Economics and Policy*, 17(1). https://www.journals.uchicago.edu/doi/10.1086/722906.
<a href="https://www.journals.uchicago.edu/doi/10.1086/722906"><button>Publication</button></a>
<a href="papers/Survey_of_empirical_ratification_literature.pdf"><button>PDF</button></a>
<a href="papers/Survey_of_empirical_ratification_literature_appendix.pdf"><button>Appendix</button></a>

**Bellelli, F.S.** and Xu, A. (2022) How do environmental policies affects green innovation and trade? Evidence from the WTO environmental database (EDB), *WTO Staff Working Paper, ERSD-2022-23*.
<a href="https://www.wto.org/english/res_e/reser_e/ersd202203_e.pdf"><button>PDF</button></a>
<a href="EDB-data.html"><button>Data</button></a>
<a href="https://drive.google.com/file/d/1sbHv8yDAyec4_CG1PPOh_RNbqLRqPNZb/view?usp=sharing"><button>Replication files</button></a>
<a href="papers/slides EAERE - Francesco Bellelli.pdf"><button>Slides</button></a>

Xu, A.,  Tresa, E., Bacchetta, **Bellelli, F.S.**, M., Monteiro, J.A. (2021) Carbon content of international trade. *World Trade Organization, Trade and climate change information brief*, n°4. Available online at: https://www.wto.org/english/news_e/news21_e/clim_03nov21-4_e.pdf. <a href="papers/WTO note trade carbon content.pdf"><button>PDF</button></a>


**Bellelli, F.S.** (2019) An overview of the main climate change agreements and the process that led to their formation. *The Foundation Journal*, Vol.XI, pp 1–15.
<a href="papers/articolo foundation published.pdf"><button>PDF</button></a>




## Contribution to books and reports

WTO (2022) World Trade Report 2022; Cliamte change and international trade. World Trade Organization. Available at: https://www.wto.org/english/res_e/publications_e/wtr22_e.htm. 
<a href="https://www.wto.org/english/res_e/booksp_e/wtr22_e/wtr22_e.pdf"><button>PDF</button></a>

Bellelli, F.S. (2022) *The Determinants of Environmental Policy and Diplomacy: An Analysis of Participation in Environmental Treaties*, Elivia Press. https://www.amazon.com/dp/9994980432

WTO (2021) *World Trade Report 2021; Economic resilience and trade*. World Trade organization. Geneva, Switzerland. Available at: https://www.wto.org/english/res_e/publications_e/wtr21_e.htm.
<a href="https://www.wto.org/english/res_e/booksp_e/wtr21_e/00_wtr21_e.pdf"><button>PDF</button></a>

<!-- Pictet (2020)  *Horizon 2020: Long-term investing in a world marked by pandemic*. Pictet WM, AA\&MR. Geneva, Switzerland. -->


## Other publications

**Bellelli, F.S.** (2022) The fascinating world of Voronoi diagrams. *Towards Data Science*. April 2. Available at: https://towardsdatascience.com/the-fascinating-world-of-voronoi-diagrams-da8fc700fa1b

*Data visualisation selected for:* Smith, A. (2019) Ten charts that tell the story of 2019. *Financial Times*. December 29. Available at: https://www.ft.com/content/62fbf660-2651-11ea-9a4f-963f0ec7e134.
<a href="papers/The great haul of China.pdf"><button>PDF</button></a>
<a href="papers/map pictet.gif"><button>GIF</button></a>

*Data visualisation for:* Johnson, S. (2019) The great haul of China, illustrated. *Financial Times*. November 19. Available online at: https://www.ft.com/content/4975eb8a-0ab6-11ea-bb52-34c8d9dc6d84.
<a href="papers/Ten charts that tell the story of 2019.pdf"><button>PDF</button></a>
<a href="papers/map pictet.gif"><button>GIF</button></a>


**Bellelli, F.S.** (2019) Understanding climate change. *New Vision*. April 11. Available online at: https://www.newvision.co.ug/new_vision/news/1498270/understanding-climate-change.
<a href="papers/climate change article new vision.pdf"><button>PDF</button></a>

**Bellelli, F.S.** (2019) The determinants of environmental policy and diplomacy; An empirical investigation of participation in environmental treaties and the influence of domestic groups. *Doctoral thesis, Durham University*. Available at: http://etheses.dur.ac.uk/13328/. 
<a href="papers/PhD thesis - Francesco S Bellelli.pdf"><button>PDF</button></a>
<a href="ratification-data.html"><button>Data</button></a>

**Bellelli, F.S.** (2015) The dynamic relationship of income with health and education spending. *Theses, Oxford Brooks University*. Available at: https://radar.brookes.ac.uk/radar/items/8e1f4895-c565-4228-9eec-65a13e87f634/1/.
<a href="papers/Tesi di laurea magistrale.pdf"><button>PDF</button></a>

**Bellelli, F.S.** (2014) Del principio della domanda effettiva in Keynes e Kalecki. *Tesi, Università degli Studi di Roma Tre*. 
<a href="papers/Tesi di laurea triennale.pdf"><button>PDF</button></a>


